//add Bill
export const ADD_BILL = 'ADD_BILL'
export const ADD_BILL_SUCCESS = 'ADD_BILL_SUCCESS'
export const ADD_BILL_ERROR = 'ADD_BILL_ERROR'
export const ADD_BILL_NULL = 'ADD_BILL_NULL'

//get Bill
export const GET_BILL = 'GET_BILL'
export const GET_BILL_SUCCESS = 'GET_BILL_SUCCESS'
export const GET_BILL_ERROR = 'GET_BILL_ERROR'

//get Bill
export const GET_BILL_BY_ID = 'GET_BILL_BY_ID'
export const GET_BILL_BY_ID_SUCCESS = 'GET_BILL_BY_ID_SUCCESS'
export const GET_BILL_BY_ID_ERROR = 'GET_BILL_BY_ID_ERROR'

//get Bill detail
export const GET_BILL_DETAIL_BY_ID = 'GET_BILL_DETAIL_BY_ID'
export const GET_BILL_DETAIL_BY_ID_SUCCESS = 'GET_BILL_DETAIL_BY_ID_SUCCESS'
export const GET_BILL_DETAIL_BY_ID_ERROR = 'GET_BILL_DETAIL_BY_ID_ERROR'