//get COMMENT
export const GET_COMMENT = 'GET_COMMENT';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_ERROR = 'GET_COMMENT_ERROR';

//ADD COMMENT
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';

//GET_COUNT COMMENT
export const GET_COUNT_COMMENT = 'GET_COUNT_COMMENT';
export const GET_COUNT_COMMENT_SUCCESS = 'GET_COUNT_COMMENT_SUCCESS';
export const GET_COUNT_COMMENT_ERROR = 'GET_COUNT_COMMENT_ERROR';
