//add FAVORITE
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS'
export const ADD_FAVORITE_ERROR = 'ADD_FAVORITE_ERROR'
export const ADD_FAVORITE_NULL = 'ADD_FAVORITE_NULL'

//get FAVORITE
export const GET_FAVORITE = 'GET_FAVORITE'
export const GET_FAVORITE_SUCCESS = 'GET_FAVORITE_SUCCESS'
export const GET_FAVORITE_ERROR = 'GET_FAVORITE_ERROR'

//get FAVORITE BY ID
export const GET_FAVORITE_BY_ID = 'GET_FAVORITE_BY_ID'
export const GET_FAVORITE_BY_ID_SUCCESS = 'GET_FAVORITE_BY_ID_SUCCESS'
export const GET_FAVORITE_BY_ID_ERROR = 'GET_FAVORITE_BY_ID_ERROR'
