//Edit Like
export const EDIT_LIKE = 'EDIT_LIKE'
export const EDIT_LIKE_SUCCESS = 'EDIT_LIKE_SUCCESS'
export const EDIT_LIKE_ERROR = 'EDIT_LIKE_ERROR'


//STATUS Like
export const STATUS_LIKE = 'STATUS_LIKE'
export const STATUS_LIKE_SUCCESS = 'STATUS_LIKE_SUCCESS'
export const STATUS_LIKE_ERROR = 'STATUS_LIKE_ERROR'

//STATUS Like
export const REMOVE_LIKE = 'REMOVE_LIKE'
export const REMOVE_LIKE_SUCCESS = 'REMOVE_LIKE_SUCCESS'
export const REMOVE_LIKE_ERROR = 'REMOVE_LIKE_ERROR'

//get like by user
export const GET_LIKE_BY_USER = 'GET_LIKE_BY_USER'
export const GET_LIKE_BY_USER_SUCCESS = 'GET_LIKE_BY_USER_SUCCESS'
export const GET_LIKE_BY_USER_ERROR = 'GET_LIKE_BY_USER_ERROR'