//get notification by user
export const GET_NOTIFICATION_BY_USER = 'GET_NOTIFICATION_BY_USER'
export const GET_NOTIFICATION_BY_USER_SUCCESS = 'GET_NOTIFICATION_BY_USER_SUCCESS'
export const GET_NOTIFICATION_BY_USER_ERROR = 'GET_NOTIFICATION_BY_USER_ERROR'