export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR'


export const GET_PRODUCT_BY_CATEGORYS = 'GET_PRODUCT_BY_CATEGORYS'
export const GET_PRODUCT_BY_CATEGORYS_SUCCESS = 'GET_PRODUCT_BY_CATEGORYS_SUCCESS'
export const GET_PRODUCT_BY_CATEGORYS_ERROR = 'GET_PRODUCT_BY_CATEGORYS_ERROR'


export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'
export const GET_PRODUCT_BY_ID_ERROR = 'GET_PRODUCT_BY_ID_ERROR'

export const GET_PRODUCT_BY_CATEGORYS_CHILD = 'GET_PRODUCT_BY_CATEGORYS_CHILD'
export const GET_PRODUCT_BY_CATEGORYS_CHILD_SUCCESS = 'GET_PRODUCT_BY_CATEGORYS_CHILD_SUCCESS'
export const GET_PRODUCT_BY_CATEGORYS_CHILD_ERROR = 'GET_PRODUCT_BY_CATEGORYS_CHILD_ERROR'
